### PR TITLE
modified template to take ldap settings

### PR DESCRIPTION
**Pull request by jseiser**

### CODE REVIEW

**Comment by jseiser** [comment]
Im not able to see why this failed?

**Comment by kbrebanov** [comment]
@jseiser 

First of all, you are only checking that **openvpn_as_module_type** is defined before including the **ldap** variables. So even if **openpvn_as_module_type** is != **ldap** those variables will be added to the configuration file.

Also, all the **openvpn_as_ldap_\*** have no default variables set and some of the LDAP related variables are missing **ldap** in their name, **users_base_dn**, **uname_attr** and **add_req**

The README also needs to be updated accordingly

**Comment by jseiser** [comment]
@kbrebanov 

Thanks!  Ill look into getting those sorted out.  I just couldnt see what actually triggered the failure so I wasnt sure what I needed to correct.

Thanks for taking the time.

**Comment by kbrebanov** [comment]
@jseiser Also, you should remove the changes related to custom SSL certs from this pull request since you have another one opened separately just for that.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.

**Pull request closed without merging**
